version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/dbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  test:
    build:
      context: .
    command: pytest tests --disable-warnings
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/dbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
